// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYBrGiX_j2cUdKZ7c39dy40RHoZgrC6U',
    appId: '1:696468649543:web:69126e383971ef24c16362',
    messagingSenderId: '696468649543',
    projectId: 'uas-cadangan',
    authDomain: 'uas-cadangan.firebaseapp.com',
    storageBucket: 'uas-cadangan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCZZbIieRVI3UDKF3Qd-esseukK1jZX8',
    appId: '1:696468649543:android:20cf9116d5db930ec16362',
    messagingSenderId: '696468649543',
    projectId: 'uas-cadangan',
    storageBucket: 'uas-cadangan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDizg4tAoJbMuX6zs9dHZkjq_7inenUcFQ',
    appId: '1:696468649543:ios:aeb5b292754bbd2ac16362',
    messagingSenderId: '696468649543',
    projectId: 'uas-cadangan',
    storageBucket: 'uas-cadangan.appspot.com',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDizg4tAoJbMuX6zs9dHZkjq_7inenUcFQ',
    appId: '1:696468649543:ios:aeb5b292754bbd2ac16362',
    messagingSenderId: '696468649543',
    projectId: 'uas-cadangan',
    storageBucket: 'uas-cadangan.appspot.com',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEYBrGiX_j2cUdKZ7c39dy40RHoZgrC6U',
    appId: '1:696468649543:web:1adfbf9fede0795fc16362',
    messagingSenderId: '696468649543',
    projectId: 'uas-cadangan',
    authDomain: 'uas-cadangan.firebaseapp.com',
    storageBucket: 'uas-cadangan.appspot.com',
  );

}