// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWb51ErgWywKoMZ5LjTzWx3-ckM5m_zz0',
    appId: '1:538461756956:web:5970a0063822fac9c789d9',
    messagingSenderId: '538461756956',
    projectId: 'uas1-478e5',
    authDomain: 'uas1-478e5.firebaseapp.com',
    storageBucket: 'uas1-478e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDybsnc6dkgCV_wpm0egub4Zcf9m--zkLc',
    appId: '1:538461756956:android:9eea9d7685a3b12bc789d9',
    messagingSenderId: '538461756956',
    projectId: 'uas1-478e5',
    storageBucket: 'uas1-478e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiryvZvOODH5biQETRVVsiDj9qFDDH8k',
    appId: '1:538461756956:ios:6a4c95d9e0ae27a0c789d9',
    messagingSenderId: '538461756956',
    projectId: 'uas1-478e5',
    storageBucket: 'uas1-478e5.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiryvZvOODH5biQETRVVsiDj9qFDDH8k',
    appId: '1:538461756956:ios:6a4c95d9e0ae27a0c789d9',
    messagingSenderId: '538461756956',
    projectId: 'uas1-478e5',
    storageBucket: 'uas1-478e5.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWb51ErgWywKoMZ5LjTzWx3-ckM5m_zz0',
    appId: '1:538461756956:web:936e14b4c7ac3a0ac789d9',
    messagingSenderId: '538461756956',
    projectId: 'uas1-478e5',
    authDomain: 'uas1-478e5.firebaseapp.com',
    storageBucket: 'uas1-478e5.appspot.com',
  );
}
